<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
      <WarningsAsErrors>;NU1605;SYSLIB0011;Nullable</WarningsAsErrors>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
      <WarningsAsErrors>;NU1605;SYSLIB0011;Nullable</WarningsAsErrors>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="OpenCvSharp4.Extensions" Version="4.13.0.20260627" />
      <PackageReference Include="OpenCvSharp4.Windows" Version="4.13.0.20260627" />
      <PackageReference Include="ZXing.Net" Version="0.16.11" />
      <PackageReference Include="ZXing.Net.Bindings.Windows.Compatibility" Version="0.16.16" />
    </ItemGroup>

</Project>
