<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Docnet.Core" Version="2.6.0" />
      <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.12" />
      <PackageReference Include="QRCoder" Version="1.8.0" />
      <PackageReference Include="System.Drawing.Common" Version="10.0.12" />
    </ItemGroup>

    <ItemGroup>
      <None Remove="Ruler\ruler-bottom.png" />
      <None Remove="Ruler\ruler-top.png" />
      <None Remove="ArUco\aruco_0.png" />
      <EmbeddedResource Include="ArUco\aruco_0.png" />
      <None Remove="ArUco\aruco_1.png" />
      <EmbeddedResource Include="ArUco\aruco_1.png" />
      <None Remove="ArUco\aruco_2.png" />
      <EmbeddedResource Include="ArUco\aruco_2.png" />
      <None Remove="ArUco\aruco_3.png" />
      <EmbeddedResource Include="ArUco\aruco_3.png" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Scanner\Scanner.csproj" />
    </ItemGroup>

</Project>
