<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>
        <AssemblyName>WorksheetToolkit</AssemblyName>
        <ApplicationIcon>Resources\Icon.ico</ApplicationIcon>
        <PackageId>WorksheetToolkit</PackageId>
        <Authors>University of Miskolc</Authors>
        <Copyright>2025, University of Miskolc</Copyright>
        <Company>University of Miskolc</Company>
        <Product>WorksheetToolkit</Product>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
      <DebugType>full</DebugType>
    </PropertyGroup>

    <ItemGroup>
      <EmbeddedResource Update="Resources\en.resx">
        <LastGenOutput>en.Designer.cs</LastGenOutput>
      </EmbeddedResource>
      <EmbeddedResource Update="Resources\Lang.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
        <LastGenOutput>Lang.Designer.cs</LastGenOutput>
      </EmbeddedResource>
      <EmbeddedResource Update="Resources\RegistryNames.resx">
        <Generator>ResXFileCodeGenerator</Generator>
        <LastGenOutput>RegistryNames.Designer.cs</LastGenOutput>
      </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Resources\Lang.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>Lang.resx</DependentUpon>
      </Compile>
      <Compile Update="Resources\RegistryNames.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>RegistryNames.resx</DependentUpon>
      </Compile>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Scanner\Scanner.csproj" />
      <ProjectReference Include="..\Storage\Storage.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Docnet.Core" Version="2.6.0" />
      <PackageReference Include="System.Drawing.Common" Version="10.0.12" />
    </ItemGroup>

</Project>
