//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Interface.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Interface.Resources.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created for the University of Miskolc..
        /// </summary>
        public static string About_1 {
            get {
                return ResourceManager.GetString("About_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third-Party Licenses:.
        /// </summary>
        public static string About_2 {
            get {
                return ResourceManager.GetString("About_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an export location.
        /// </summary>
        public static string Browse_ExportTitle {
            get {
                return ResourceManager.GetString("Browse_ExportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach image to question.
        /// </summary>
        public static string Browse_ImageImportTitle {
            get {
                return ResourceManager.GetString("Browse_ImageImportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a file to Import.
        /// </summary>
        public static string Browse_ImportTitle {
            get {
                return ResourceManager.GetString("Browse_ImportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save results.
        /// </summary>
        public static string Browse_SolveExportTitle {
            get {
                return ResourceManager.GetString("Browse_SolveExportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a scan to Import.
        /// </summary>
        public static string Browse_SolveImportTitle {
            get {
                return ResourceManager.GetString("Browse_SolveImportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Common_Error {
            get {
                return ResourceManager.GetString("Common_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled exception occurred, and the program will close..
        /// </summary>
        public static string Crash_Message {
            get {
                return ResourceManager.GetString("Crash_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured!.
        /// </summary>
        public static string Crash_Title {
            get {
                return ResourceManager.GetString("Crash_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount:.
        /// </summary>
        public static string Export_Amount {
            get {
                return ResourceManager.GetString("Export_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer count:.
        /// </summary>
        public static string Export_AnswerCount {
            get {
                return ResourceManager.GetString("Export_AnswerCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author:.
        /// </summary>
        public static string Export_Author {
            get {
                return ResourceManager.GetString("Export_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Export_Browse {
            get {
                return ResourceManager.GetString("Export_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        public static string Export_Date {
            get {
                return ResourceManager.GetString("Export_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuffle Exceptions:.
        /// </summary>
        public static string Export_Exceptions {
            get {
                return ResourceManager.GetString("Export_Exceptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export PDF.
        /// </summary>
        public static string Export_Export {
            get {
                return ResourceManager.GetString("Export_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not export:.
        /// </summary>
        public static string Export_ExportFailed {
            get {
                return ResourceManager.GetString("Export_ExportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export saved.
        /// </summary>
        public static string Export_ExportSaved {
            get {
                return ResourceManager.GetString("Export_ExportSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string Export_High {
            get {
                return ResourceManager.GetString("Export_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified target path is invalid..
        /// </summary>
        public static string Export_InvalidPath {
            get {
                return ResourceManager.GetString("Export_InvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string Export_Low {
            get {
                return ResourceManager.GetString("Export_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string Export_Med {
            get {
                return ResourceManager.GetString("Export_Med", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep answer order.
        /// </summary>
        public static string Export_Ordered {
            get {
                return ResourceManager.GetString("Export_Ordered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export path:.
        /// </summary>
        public static string Export_Path {
            get {
                return ResourceManager.GetString("Export_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Preview.
        /// </summary>
        public static string Export_Preview {
            get {
                return ResourceManager.GetString("Export_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution:.
        /// </summary>
        public static string Export_Resolution {
            get {
                return ResourceManager.GetString("Export_Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuffle answer order.
        /// </summary>
        public static string Export_Shuffle {
            get {
                return ResourceManager.GetString("Export_Shuffle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shuffle answer order, with exceptions.
        /// </summary>
        public static string Export_ShuffleSmart {
            get {
                return ResourceManager.GetString("Export_ShuffleSmart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export completed successfully!.
        /// </summary>
        public static string Export_Success {
            get {
                return ResourceManager.GetString("Export_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        public static string Export_Title {
            get {
                return ResourceManager.GetString("Export_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export_WindowLabel {
            get {
                return ResourceManager.GetString("Export_WindowLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom In.
        /// </summary>
        public static string Export_ZoomIn {
            get {
                return ResourceManager.GetString("Export_ZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom Out.
        /// </summary>
        public static string Export_ZoomOut {
            get {
                return ResourceManager.GetString("Export_ZoomOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not every question on the sheet has been set (A question is set to &apos;...&apos;)!
        ///Continue anyway?.
        /// </summary>
        public static string ExportError_HasNull {
            get {
                return ResourceManager.GetString("ExportError_HasNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided question(s) ha(ve|s) more than 1 solution:
        ///#ERR#.
        /// </summary>
        public static string ExportError_ManySolutions {
            get {
                return ResourceManager.GetString("ExportError_ManySolutions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of questions may not be more than #MAX#!.
        /// </summary>
        public static string ExportError_MayBeTooMany {
            get {
                return ResourceManager.GetString("ExportError_MayBeTooMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of questions may not be 0!.
        /// </summary>
        public static string ExportError_MayBeZero {
            get {
                return ResourceManager.GetString("ExportError_MayBeZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of questions may not be 0 or more than #MAX#!.
        /// </summary>
        public static string ExportError_MayBeZeroOrTooMany {
            get {
                return ResourceManager.GetString("ExportError_MayBeZeroOrTooMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of questions is not an exact number!
        ///Continue anyway?.
        /// </summary>
        public static string ExportError_NonConst {
            get {
                return ResourceManager.GetString("ExportError_NonConst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided question(s) ha(ve|s) less than 5 answers:
        ///#ERR#
        ///
        ///Continue anyway?.
        /// </summary>
        public static string ExportError_NotEnoughAnswers {
            get {
                return ResourceManager.GetString("ExportError_NotEnoughAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided question(s)ha(ve|s) 1 answer:
        ///#ERR#.
        /// </summary>
        public static string ExportError_OneAnswer {
            get {
                return ResourceManager.GetString("ExportError_OneAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided question(s) ha(ve|s) more been added more than once to the test sheet:
        ///#ERR#
        ///
        ///Continue anyway?.
        /// </summary>
        public static string ExportError_RepeatedQuestion {
            get {
                return ResourceManager.GetString("ExportError_RepeatedQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided question(s) ha(ve|s) no answers:
        ///#ERR#.
        /// </summary>
        public static string ExportError_ZeroAnswer {
            get {
                return ResourceManager.GetString("ExportError_ZeroAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided question(s) ha(ve|s) no solution(s):
        ///#ERR#.
        /// </summary>
        public static string ExportError_ZeroSolution {
            get {
                return ResourceManager.GetString("ExportError_ZeroSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting....
        /// </summary>
        public static string ExportPopup_Exporting {
            get {
                return ResourceManager.GetString("ExportPopup_Exporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Import_Browse {
            get {
                return ResourceManager.GetString("Import_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Import_Confirm {
            get {
                return ResourceManager.GetString("Import_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path:.
        /// </summary>
        public static string Import_File {
            get {
                return ResourceManager.GetString("Import_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import an existing Database.
        /// </summary>
        public static string Import_Title {
            get {
                return ResourceManager.GetString("Import_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MenuTabs_About {
            get {
                return ResourceManager.GetString("MenuTabs_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correction.
        /// </summary>
        public static string MenuTabs_Correct {
            get {
                return ResourceManager.GetString("MenuTabs_Correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string MenuTabs_Export {
            get {
                return ResourceManager.GetString("MenuTabs_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheets.
        /// </summary>
        public static string MenuTabs_Sheets {
            get {
                return ResourceManager.GetString("MenuTabs_Sheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        public static string MenuTabs_Tasks {
            get {
                return ResourceManager.GetString("MenuTabs_Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter code.
        /// </summary>
        public static string Missing_EnterCode {
            get {
                return ResourceManager.GetString("Missing_EnterCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered exam code is not valid!.
        /// </summary>
        public static string Missing_ExamCode {
            get {
                return ResourceManager.GetString("Missing_ExamCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Exam code....
        /// </summary>
        public static string Missing_ExamHint {
            get {
                return ResourceManager.GetString("Missing_ExamHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered Neptun code is not valid!.
        /// </summary>
        public static string Missing_Neptun {
            get {
                return ResourceManager.GetString("Missing_Neptun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Neptun code....
        /// </summary>
        public static string Missing_NeptunHint {
            get {
                return ResourceManager.GetString("Missing_NeptunHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan result is not valid!.
        /// </summary>
        public static string Missing_ResultInvalid {
            get {
                return ResourceManager.GetString("Missing_ResultInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        public static string Missing_Skip {
            get {
                return ResourceManager.GetString("Missing_Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page has failed to parse some data, and needs to be filled manually!.
        /// </summary>
        public static string Missing_Title {
            get {
                return ResourceManager.GetString("Missing_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Data Form.
        /// </summary>
        public static string Missing_WindowTitle {
            get {
                return ResourceManager.GetString("Missing_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Password_Change {
            get {
                return ResourceManager.GetString("Password_Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        public static string Password_Enter {
            get {
                return ResourceManager.GetString("Password_Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is incorrect..
        /// </summary>
        public static string Password_Failure {
            get {
                return ResourceManager.GetString("Password_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter password:.
        /// </summary>
        public static string Password_Label {
            get {
                return ResourceManager.GetString("Password_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string Password_New {
            get {
                return ResourceManager.GetString("Password_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New database created successfully..
        /// </summary>
        public static string PasswordResult_CreatedSuccess {
            get {
                return ResourceManager.GetString("PasswordResult_CreatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database could no longer be found, please update the import path..
        /// </summary>
        public static string PasswordResult_DefaultFileMissing {
            get {
                return ResourceManager.GetString("PasswordResult_DefaultFileMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database imported successfully..
        /// </summary>
        public static string PasswordResult_ImportedSuccess {
            get {
                return ResourceManager.GetString("PasswordResult_ImportedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to import database, maybe the path is invalid?.
        /// </summary>
        public static string PasswordResult_ImportFailed {
            get {
                return ResourceManager.GetString("PasswordResult_ImportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path may not be empty..
        /// </summary>
        public static string PasswordResult_InvalidPath {
            get {
                return ResourceManager.GetString("PasswordResult_InvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Setup_Back {
            get {
                return ResourceManager.GetString("Setup_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Setup_Browse {
            get {
                return ResourceManager.GetString("Setup_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Setup_Confirm {
            get {
                return ResourceManager.GetString("Setup_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path:.
        /// </summary>
        public static string Setup_File {
            get {
                return ResourceManager.GetString("Setup_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least 8 character long passwords are recommended..
        /// </summary>
        public static string Setup_Hint {
            get {
                return ResourceManager.GetString("Setup_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string Setup_Password {
            get {
                return ResourceManager.GetString("Setup_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new Database.
        /// </summary>
        public static string Setup_Title {
            get {
                return ResourceManager.GetString("Setup_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add question group.
        /// </summary>
        public static string Sheet_AddContainer {
            get {
                return ResourceManager.GetString("Sheet_AddContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add question.
        /// </summary>
        public static string Sheet_AddQuestion {
            get {
                return ResourceManager.GetString("Sheet_AddQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string Sheet_ContainerTitle {
            get {
                return ResourceManager.GetString("Sheet_ContainerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Sheet_Delete {
            get {
                return ResourceManager.GetString("Sheet_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        public static string Sheet_Hide {
            get {
                return ResourceManager.GetString("Sheet_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List all in order.
        /// </summary>
        public static string Sheet_OptionListOrdered {
            get {
                return ResourceManager.GetString("Sheet_OptionListOrdered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List all shuffled.
        /// </summary>
        public static string Sheet_OptionListShuffled {
            get {
                return ResourceManager.GetString("Sheet_OptionListShuffled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick 1 randomly.
        /// </summary>
        public static string Sheet_OptionPickRandom {
            get {
                return ResourceManager.GetString("Sheet_OptionPickRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string Sheet_QuestionTitle {
            get {
                return ResourceManager.GetString("Sheet_QuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task sheet.
        /// </summary>
        public static string Sheet_RootTitle {
            get {
                return ResourceManager.GetString("Sheet_RootTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select question.
        /// </summary>
        public static string Sheet_SelectQuestion {
            get {
                return ResourceManager.GetString("Sheet_SelectQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string Sheet_Show {
            get {
                return ResourceManager.GetString("Sheet_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting PDF.
        /// </summary>
        public static string Solve_ExportingPdf {
            get {
                return ResourceManager.GetString("Solve_ExportingPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export results by sheet....
        /// </summary>
        public static string Solve_Get {
            get {
                return ResourceManager.GetString("Solve_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export results by task....
        /// </summary>
        public static string Solve_GetAlt {
            get {
                return ResourceManager.GetString("Solve_GetAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export with confidence.
        /// </summary>
        public static string Solve_IncludeConfidence {
            get {
                return ResourceManager.GetString("Solve_IncludeConfidence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select file....
        /// </summary>
        public static string Solve_Select {
            get {
                return ResourceManager.GetString("Solve_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Task.
        /// </summary>
        public static string Task_Add {
            get {
                return ResourceManager.GetString("Task_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Answer.
        /// </summary>
        public static string Task_AddAnswer {
            get {
                return ResourceManager.GetString("Task_AddAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer.
        /// </summary>
        public static string Task_Answer {
            get {
                return ResourceManager.GetString("Task_Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct.
        /// </summary>
        public static string Task_AnswerCorrect {
            get {
                return ResourceManager.GetString("Task_AnswerCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answers:.
        /// </summary>
        public static string Task_Answers {
            get {
                return ResourceManager.GetString("Task_Answers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Selected Task.
        /// </summary>
        public static string Task_Delete {
            get {
                return ResourceManager.GetString("Task_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Selected Answer.
        /// </summary>
        public static string Task_DeleteAnswer {
            get {
                return ResourceManager.GetString("Task_DeleteAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string Task_HasImage {
            get {
                return ResourceManager.GetString("Task_HasImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Image.
        /// </summary>
        public static string Task_Image {
            get {
                return ResourceManager.GetString("Task_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Image.
        /// </summary>
        public static string Task_ImageDelete {
            get {
                return ResourceManager.GetString("Task_ImageDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attached Image.
        /// </summary>
        public static string Task_ImageLabel {
            get {
                return ResourceManager.GetString("Task_ImageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        public static string Task_Points {
            get {
                return ResourceManager.GetString("Task_Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string Task_Question {
            get {
                return ResourceManager.GetString("Task_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question:.
        /// </summary>
        public static string Task_QuestionLabel {
            get {
                return ResourceManager.GetString("Task_QuestionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score:.
        /// </summary>
        public static string Task_Score {
            get {
                return ResourceManager.GetString("Task_Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Task_Select {
            get {
                return ResourceManager.GetString("Task_Select", resourceCulture);
            }
        }
    }
}
